main:
   kick-message: '[PREFIX][NEWLINE]Suspicious activity'
   kicks-to-ban: 3
   ban-command: 'minecraft:ban [PLAYER] [PREFIX][NEWLINE]You were caught cheating!'
   limiter-removal-rate: 1
   flag-removal-rate: 30
   join-bypass-ticks: 170
   cancel-event: true
checks:
  speed:
    a:
      enabled: false
      ice-increase: 0.3
      maximum-speed: 0.95
      flags-to-kick: 5
    b:
      enabled: false
      ice-increase: 0.11
      slime-increase: 0.04
      too-little-friction: 0.51
      flags-to-kick: 6
  fly:
    a:
      enabled: true
      limiter: 3
      flags-to-kick: 5
    b:
      enabled: true
      limiter: 3
      descend: -0.1
      fall-height: 1
      flags-to-kick: 8
    c:
      enabled: true
      limiter: 3
      fall-height: 1
      flags-to-kick: 5
    d:
      enabled: true
      limiter: 2
      smallest-descend: 0.3
      fall-distance: 0.4
      flags-to-kick: 12
  fastplace:
    a:
      enabled: true
      maxplace: 5
      place-removal-rate-ticks: 2
      flags-to-kick: 3
  impossibleactions:
    a:
      enabled: true
      limiter: 3
      flags-to-kick: 8
    b:
      enabled: true
      flags-to-kick: 1
  noslowdown:
    a:
      enabled: true
      ice-increase: 0.11
      maxspeed: 0.2153
      flags-to-kick: 4
  jesus:
    a:
      enabled: true
      nearby-boat-radius: 2
      flags-to-kick: 5
    b:
      enabled: true
      max-ascend: 2
      flags-to-kick: 3
    c:
      enabled: true
      limiter: 3
      flags-to-kick: 8
    d:
      enabled: true
      max-ascend: 0.1
      flags-to-kick: 5
  invmove:
    a:
      enabled: true
      ticks-since-damage: 5
      max-speed: 0.1
      flags-to-kick: 5
  groundspoof:
    a:
      enabled: true
      nearby-boat-radius: 2
      flags-to-kick: 6
    b:
      enabled: true
      limiter: 5
      flags-to-kick: 3
    c:
      enabled: true
      limiter: 3
      flags-to-kick: 5
  elytrafly:
    a:
      enabled: true
      ticks-since-rocket: 100
      flags-to-kick: 4
    b:
      enabled: true
      ticks-since-rocket: 100
      flags-to-kick: 4
  reach:
    a:
      enabled: true
      max-reach: 4.4
      creative-increase: 2.6
      flags-to-kick: 8
